reupload of assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #100
Opened 2023-11-21 11:19 UTC by NestorRovira

2023-11-21 23:05 UTC, dgarijo requested changes
Please address the remaining comments

2023-11-21 23:05 UTC, dgarijo commented on Assignment4/nestor_rovira-22c057/Task07.py
> +?sub rdfs:subClassOf ns:LivingThing.
this does not retrieve subclasses of subclasses of living thing

2023-11-21 23:05 UTC, dgarijo commented on Assignment4/nestor_rovira-22c057/Task07.py
> +{?sub rdfs:subClassOf ns:Person. ?individuals a ?sub}
same as above

2023-11-21 23:05 UTC, dgarijo commented on Assignment4/nestor_rovira-22c057/Task07.py
> +?individuals ?property ?value.
this is not doing what the exercise asks for

2023-11-21 23:05 UTC, dgarijo commented on Assignment4/nestor_rovira-22c057/Task07.py
> +?individuals foaf:knows ns:RockySmith.
the exercise is asking for names, not uris

2023-11-21 23:05 UTC, dgarijo commented on Assignment4/nestor_rovira-22c057/Task07.py
> +
missing all exercises in rdflib

2023-11-23 21:52 UTC, anaigmo commented
Entregado sin corregir los comentarios, no se admiten más PR

2023-11-23 21:52 UTC, merged