Assign. 4
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #103
Opened 2023-11-21 14:50 UTC by gallegomiguel

Hola, soy Miguel Gallego y envié la tarea a través de Moodle en su momento. La envío por aquí para la corrección. Un saludo.

2023-11-21 23:17 UTC, dgarijo requested changes
You are missing some details. Review them please

2023-11-21 23:17 UTC, dgarijo commented on Assignment4/gallegomiguel-22c052/wkg_task06_fin.py
> +g.add((ns.JaneSmith, vcard.Orgname, ns.UPM))
nicely done. However orgName links to the organization name, not the organization URI per se.

2023-11-21 23:17 UTC, dgarijo commented on Assignment4/gallegomiguel-22c052/wkg_task07_fin.py
> +  ?SubC rdfs:subClassOf ns:LivingThing.
missing subclasses of subclasses of living thing

2023-11-21 23:17 UTC, dgarijo commented on Assignment4/gallegomiguel-22c052/wkg_task06_fin.py
> +g.add((ns.JaneSmith, vcard.Orgname, ns.UPM))
`vcard:ORG` would be more fitting, in my opinion

2023-11-21 23:17 UTC, dgarijo commented on Assignment4/gallegomiguel-22c052/wkg_task07_fin.py
> +}
the exercise asks for a name, not a uri

2023-11-21 23:17 UTC, dgarijo commented on Assignment4/gallegomiguel-22c052/wkg_task07_fin.py
> +
complete 7.1 .. 7.5 in rdflib please

2023-11-22 14:21 UTC, gallegomiguel commented on Assignment4/gallegomiguel-22c052/wkg_task06_fin.py
> +g.add((ns.JaneSmith, vcard.Orgname, ns.UPM))
I've tried but says '`invalid syntax`' regarding `vcard:ORG`

2023-11-23 21:40 UTC, anaigmo commented
Entregado y corregido con algunos errores, no se admiten más PR

2023-11-23 21:40 UTC, merged