Assignment 1 Gloria Domingo
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #31
Opened 2023-09-25 22:37 UTC by gloriadomingo

Assignment 1 Gloria Domingo

2023-11-13 17:05 UTC, dgarijo requested changes
Please address these problems

2023-11-13 17:05 UTC, dgarijo commented on Assignment4/gloriadomingo-22C026/task06.py
> +g.add((ns.JaneSmith, RDFS.Literal, ns.Researcher))
that's not the right relationship to declare individuals

2023-11-13 17:05 UTC, dgarijo commented on Assignment4/gloriadomingo-22C026/task06.py
> +g.add((ns.Jown, ns.knowsJaneuses, ns.FOAFvocabulary))
What is `knowsJaneuses`?? it's not in the FOAF namespace. Also,  ns.FOAFvocabulary is unrelated!

2023-11-13 17:05 UTC, dgarijo commented on Assignment4/gloriadomingo-22C026/task07.py
> +  print(r)
missing all subclasses of Living thing

2023-11-13 17:05 UTC, dgarijo commented on Assignment4/gloriadomingo-22C026/task07.py
> +    print(persona)
you need to make this method recursive.

2023-11-13 17:05 UTC, dgarijo commented on Assignment4/gloriadomingo-22C026/task07.py
> +  print(s)
missing all subclasses. You need to make this method recursive

2023-11-13 17:05 UTC, dgarijo commented on Assignment4/gloriadomingo-22C026/task07.py
> +    ?x ?relacion ?a
What about Person?

2023-11-13 17:05 UTC, dgarijo commented on Assignment4/gloriadomingo-22C026/task07.py
> +    ?x FOAF:knows ns:RockySmith
you are not listing the name of the person

2023-11-13 17:05 UTC, dgarijo commented on Assignment4/gloriadomingo-22C026/task07.py
> +    ?x FOAF:knows ?y
this lists all the entities who know another. This is not what was requested

2023-11-23 23:11 UTC, anaigmo commented
Entregado con errores, no se admiten más PR

2023-11-23 23:12 UTC, merged