Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #33
Opened 2023-10-15 13:42 UTC by danillopis

2023-10-31 16:19 UTC, SerPablo reviewed
Please review results for tasks 7.4 and 7.5. Im not able to reproduce them

2023-10-31 16:19 UTC, SerPablo commented on Assignment4/d.llopis-21C033/task07.py
> +    }''',
This query does not retrieve anything

2023-11-04 16:56 UTC, danillopis reviewed
creo que ya está corregido

2023-11-04 17:00 UTC, dgarijo commented
- @danillopis Remove the .DSStore and .Rhistory files from the repo.
- Have you run the query? Because you are defining the foaf vocabulary in SPARQL, but you are not declaring the namespace anywhere. The query should not run. Run the query and then review the PR

2023-11-04 17:17 UTC, danillopis commented
I don't know how to remove those files just cause they don't appear on my own repository. And yes, I ran the code before on gcollab and it apparently run.

2023-11-04 17:19 UTC, danillopis commented
Maybe those files were created after the changes, i don't know why

2023-11-04 17:21 UTC, dgarijo commented
Those files are generated in your machine, otherwise they would not be part of the PR. They are invisible though, so you have to configure your machine to view them

2023-11-04 17:21 UTC, dgarijo commented
You have not deleted them from your folder but you still have them in the parent one. Also, you are modifying a readme file that you should not

2023-11-04 17:22 UTC, dgarijo commented
you are also missing the exercises in RDFlib (you only provide the sparql solution)

2023-11-04 18:01 UTC, danillopis commented
I think now is all right. When you can if you can check it, it would be grateful.

2023-11-14 22:59 UTC, dgarijo requested changes
You need to remove changes to the README, the HandsOn and leave ONLY your d.llopis file.
You are close to the solutions, but need a bit more work

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/task06corr.py
> +g.add((JaneSmith, ns3.gIVEN, given_name))
GIVEN

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/task06corr.py
> +ns7 = Namespace("http://somewhere")
why do you keep re-declaring the namespace? Each NS should be declared only once

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/task06corr.py
> +JaneSmith = ns.JaneSmith
Same thing for John and Jane, you already defined them above

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/trask07corr.py
> +    ?subClase rdfs:subClassOf ns:LivingThing
You are not listing all subclasses of subclasses of living thing (recursively). Use `*`

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/trask07corr.py
> +            subclasses.add(sub)
You are not tracking the full subclass hierarchy, as happened before. Hint: make a recursive function

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/trask07corr.py
> +    classes_to_include.add(subject)
you are not adding all subclasses. For example, if something is a subclass of a subclass of person

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/trask07corr.py
> +     ?individual rdf:type/rdfs:subClassOf* ?class .
With this you are listing the individuals of the subclasses of person. You need to remove `*` in this case

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/trask07corr.py
> +     ?individual rdf:type/rdfs:subClassOf* ?class .
also, use UNION, not filter, as it's very inefficient here.

2023-11-14 22:59 UTC, dgarijo commented on Assignment4/d.llopis-21C033/trask07corr.py
> +        ?person foaf:knows ns:RockySmith .
you are not listing the name of the persons, just their URI

2023-11-19 12:49 UTC, danillopis commented
Hi, I think now it's everything OK...

2023-11-20 11:50 UTC, dgarijo commented
You are removing the README files of the main repository, which is incorrect. Please only add the files you want us to review

2023-11-20 11:51 UTC, dgarijo commented
Also, you are not following the instructions shown in class. You have to create a folder with your id, not replace the files in Assignment4. Once you follow the instructions, let us know

2023-11-20 16:39 UTC, danillopis commented
Is it correct now? Sorry for all the inconvenience

2023-11-21 22:28 UTC, dgarijo requested changes
You have it mostly ok, very minor issues pending

2023-11-21 22:28 UTC, dgarijo commented on Assignment4/danillopis - 21C033/trask07corr.py
> +for s,p,o in g.triples((None, RDFS.subClassOf, ns.Person)):
you have to also do a recursive function here, unless you use your previously define recursive function to get the classes

2023-11-21 22:28 UTC, dgarijo commented on Assignment4/danillopis - 21C033/trask07corr.py
> +
missing exercise in rdflib

2023-11-21 22:28 UTC, dgarijo commented on Assignment4/danillopis - 21C033/trask07corr.py
> +  print(s)
This is not correct. You have to return the name, as you do below

2023-11-22 13:29 UTC, danillopis commented
I hope it's ok. Sorry for all the inconvenience.

2023-11-23 23:16 UTC, anaigmo commented
Entregado y corregido

2023-11-23 23:17 UTC, merged