Assignment4
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #37
Opened 2023-10-16 17:04 UTC by AlejandroGil14

2023-11-13 16:44 UTC, dgarijo requested changes
Please see comments about errors and missing things

2023-11-13 16:44 UTC, dgarijo commented on task06.py
> +"""Copia de Task06.ipynb
Remove this file. Leave only the ones in your folder

2023-11-13 16:44 UTC, dgarijo commented on AlejandrGil14-22c054/task06
> +
File has the incorrect extension

2023-11-13 16:44 UTC, dgarijo commented on AlejandrGil14-22c054/task06
> +resource = (janeURI ,ns.Researcher, fullName)
The property used is incorrect. You are adding a class as a property!

2023-11-13 16:44 UTC, dgarijo commented on AlejandrGil14-22c054/task06
> +email=(janeURI, vcard.EMAIL, Literal('jsmith@example.org'))
We have repeatedly shown in class the importance of adding xsd types in literals. Please follow those guidelines.

2023-11-13 16:44 UTC, dgarijo commented on AlejandrGil14-22c054/task06
> +relacion = (JohnUri, vcard.WorksAt, UPM_uri)
vcard does not have a `WorksAt` property

2023-11-23 23:24 UTC, anaigmo commented
Entregado pero faltan ejercicios, no se admiten más PR

2023-11-23 23:24 UTC, merged