Assignment4 Alexandru Filimon
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #38
Opened 2023-10-16 17:09 UTC by alejandroFili

2023-11-13 16:55 UTC, dgarijo requested changes
Please address my comments

2023-11-13 16:55 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task07.py
> +    ?subClase rdfs:subClassOf ns:LivingThing
missing all subclasses of LivingThing

2023-11-13 16:55 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task07.py
> +    ?person rdf:type ns:Person
Missing individuals from all subclasses

2023-11-13 16:55 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task07.py
> +)
Very inefficient. Use an UNION instead.

2023-11-13 16:55 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task07.py
> +for r in g.query(query_5):
missing all exercises in rdflib

2023-11-20 20:43 UTC, alejandroFili commented on Assignment4/alejandroFili - 22C012/task07.py
> +    ?subClase rdfs:subClassOf ns:LivingThing
solved by using subClassOf*

2023-11-20 20:44 UTC, alejandroFili commented on Assignment4/alejandroFili - 22C012/task07.py
> +    ?person rdf:type ns:Person
solved by using rdf:type/rdfs:subClassOf*

2023-11-20 20:44 UTC, alejandroFili commented on Assignment4/alejandroFili - 22C012/task07.py
> +)
restructured to a version using UNION

2023-11-20 20:45 UTC, alejandroFili commented on Assignment4/alejandroFili - 22C012/task07.py
> +for r in g.query(query_5):
By all I understand 7.1, 7.2, 7.3.
Added versions using directly rdflib

2023-11-21 22:38 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task07.py
> +for r in g.query(query_5):
no, also 7.4 and 7.5. We also request them, sorry

2023-11-21 22:42 UTC, dgarijo requested changes
Almost there! please address remaining changes

2023-11-21 22:42 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task06.py
> +g.add((ns.JaneSmith, VCARD["given-name"] , Literal("Jane")))
given-name is not defined in VCARD. Why don't you use `Given`? Same for the others below. Have a look at the vocabulary and look for the right properties

2023-11-21 22:42 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task07.py
> +     FILTER(?given_name = "Rocky")
the query is very convoluted. Why not just using the literal instead of given_name?

You can do ?rocky vcard:Given "Rocky"

2023-11-22 10:19 UTC, alejandroFili commented on Assignment4/alejandroFili - 22C012/task07.py
> +for r in g.query(query_5):
also added

2023-11-22 10:22 UTC, alejandroFili commented on Assignment4/alejandroFili - 22C012/task06.py
> +g.add((ns.JaneSmith, VCARD["given-name"] , Literal("Jane")))
Back then I googled the vocabulary, and as you can see [here](https://www.w3.org/TR/vcard-rdf/) and [here](https://www.w3.org/2006/vcard/ns) they have replaced Given and Family with the values I used.
Nevertheless i have changed them to match the 2001 version.

2023-11-22 10:29 UTC, alejandroFili commented on Assignment4/alejandroFili - 22C012/task07.py
> +     FILTER(?given_name = "Rocky")
- vcard: since nobody explained us beforehand the difference between `# `and `/ ` when I tried to create the `VCARD ` variable I tried it with `#` and without it, but not with a final `/` so the `vcard:Given` didn't work
- "Rocky" does not work I actually needed `"Rocky"^^xsd:string` , I figured that out when I tried to do the rdflib only and I had to put the `datatype `to the `Literal`

2023-11-23 23:20 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task06.py
> +g.add((ns.JaneSmith, VCARD["given-name"] , Literal("Jane")))
You just need to resolve the vocabulary you are using and see what is described there

2023-11-23 23:23 UTC, dgarijo commented on Assignment4/alejandroFili - 22C012/task07.py
> +     FILTER(?given_name = "Rocky")
You need the ^^xsd:string indeed, I usually describe a template of the solution, not the full solution itself.

If the example is using `/` then we are using the incorrect namespace.

2023-11-23 23:24 UTC, dgarijo approved these changes
nice job

2023-11-23 23:24 UTC, merged