Assignment 4, Martina Valdivielso
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #39
Opened 2023-10-16 18:46 UTC by martinavaldivielso

2023-11-13 16:37 UTC, dgarijo requested changes
There are incomplete exercises. Please address all comments

2023-11-13 16:37 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task06.py
> +g.add((ns.JohnSmith, VCARD.worksat, ns.UPM))
this property does not exist in vcard. you have to either find one that exists or create your won

2023-11-13 16:37 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +      ?subClass rdfs:subClassOf ns:LivingThing
this does not consider all subclasses of subclasses of LivingThing

2023-11-13 16:37 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +        ?individual rdf:type ?x
same as above

2023-11-13 16:37 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +      }
The query does not ask for Living thing. Please do what the exercise says

2023-11-13 16:37 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +
All exercises are missing in rdflib

2023-11-13 22:09 UTC, martinavaldivielso commented
ya he actualizado los dos ficheros, hice el commit en el github desktop y el push origin, pero no me deja hacer un pull request de los nuevos archivos.
¿Cómo puedo subir los cambios?

2023-11-14 23:13 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +      ?subClass rdfs:subClassOf ns:LivingThing
Your change still does not address the issue. You need to use property chains with `*`

2023-11-14 23:18 UTC, dgarijo requested changes
Almost there but need additional changes

2023-11-14 23:18 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +        ?y rdfs:subClassOf ns:LivingThing.
The exercise asks to use Person and Animal, not living thing. You need a UNION query

2023-11-14 23:18 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +    entities.append(s)
You are not checking that the same subject knows 2 different people

2023-11-14 23:18 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +        ?individual rdf:type ?x
Use a/subclassOf*

2023-11-14 23:18 UTC, dgarijo commented on Assignment4/martinavaldivielso-22c019/copia_de_task07.py
> +  print(s)
Use a recursive function to list all subclasses, this only prints one level

2023-11-15 08:57 UTC, martinavaldivielso commented
es necesario hacer una función recursiva para mostrar todos los niveles? es que si hago 3 for anidados me sale bien, pero si intento hacer la función no me imprime nada

2023-11-15 09:13 UTC, martinavaldivielso commented
ya he conseguido hacer la función; sin embargo, en ese mismo ejercicio al hacerlo con sparql si uso rdfs:subClassOf* me devuelve también (rdflib.term.URIRef('[http://somewhere#LivingThing](http://somewhere/#LivingThing)'),) cuando lo imprimo. ¿A qué se debe? si le estoy indicando que sea una subclase

2023-11-15 13:11 UTC, dgarijo commented
La idea que tienes es la correcta, pero creo que te haces algo de lio con el set.
Mi solucion es:
```
def printSubClasses(c):
  for s, p, o in g.triples((None, RDFS.subClassOf, c)):
    print(s)
    printSubClasses(s)

print("Print results using RDFLib")
printSubClasses(ns.LivingThing)
```

2023-11-15 13:15 UTC, merged

2023-11-15 16:05 UTC, martinavaldivielso commented
y no tengo que almacenarlo en alguna variable? es que yo había creado el conjunto para irlo actualizando y metiendo mis nuevas llamadas a la función. Así al llamarla obtenía todas las subclases y luego las imprimía con el for