Assignment 4 - Laura Martín
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #43
Opened 2023-10-16 20:27 UTC by LLLP11

task 6 and 7

2023-11-13 17:25 UTC, dgarijo requested changes
Please see pending changes to address

2023-11-13 17:25 UTC, dgarijo commented on LLLP11 - 22C005/task06.py
> +g.add((ns.JaneSmith, RDFS.Literal, ns.Researcher))
This is incorrect. RDFS.Literal is not used to create individuals

2023-11-13 17:25 UTC, dgarijo commented on LLLP11 - 22C005/task06.py
> +g.add((ns.UPM, RDFS.Literal, ns.University))
wrong again

2023-11-13 17:25 UTC, dgarijo commented on LLLP11 - 22C005/task06.py
> +g.add((ns.Jown, ns.knowsJaneuses, ns.FOAFvocabulary))
I do not know what are you trying to do here.

2023-11-13 17:25 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +q1 = prepareQuery("SELECT ?x WHERE {?x rdfs:subClassOf ns:LivingThing}", initNs = {"rdfs": RDFS, "ns": ns})
missing all subclasses of LivingThing

2023-11-13 17:25 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +    print(persona)
Make the method recursive or you'll see a discrepancy in the responses

2023-11-13 17:25 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +    ?x ?relacion ?a
What about the persons?

2023-11-13 17:25 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +    ?x FOAF:knows ns:RockySmith
You are asked to list the name of the persons

2023-11-13 17:25 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +    ?x FOAF:knows ?y
You are not listing the entities that know at least two persons. You are listing the ones that know any person

2023-11-19 14:29 UTC, LLLP11 commented on LLLP11 - 22C005/task06.py
> +g.add((ns.JaneSmith, RDFS.Literal, ns.Researcher))
I've changed RDFS.Literal to RDF.type

g.add((ns.JaneSmith, **RDF.type**, ns.Researcher))
for s, p, o in g:
  print(s,p,o)

2023-11-19 14:30 UTC, LLLP11 commented on LLLP11 - 22C005/task06.py
> +g.add((ns.UPM, RDFS.Literal, ns.University))
g.add((ns.UPM, **RDF.type,** ns.University))
g.add((ns2.works_at, RDF.type, RDFS.Datatype))
g.add((ns.JohnSmith, ns2.works_at, ns.UPM))
for s, p, o in g:
  print(s,p,o)

2023-11-19 14:31 UTC, LLLP11 commented on LLLP11 - 22C005/task06.py
> +g.add((ns.Jown, ns.knowsJaneuses, ns.FOAFvocabulary))
I've changed the code:
**foaf=Namespace("http://xmlns.com/foaf/0.1/")
g.add((ns.JohnSmith, RDF.type, foaf.Person))
g.add((ns.JaneSmith, RDF.type, foaf.Person))
g.add((ns.JohnSmith, foaf.knows, ns.JaneSmith))**
for s, p, o in g:
  print(s,p,o)

2023-11-19 14:36 UTC, LLLP11 commented on LLLP11 - 22C005/task07.py
> +q1 = prepareQuery("SELECT ?x WHERE {?x rdfs:subClassOf ns:LivingThing}", initNs = {"rdfs": RDFS, "ns": ns})
Added * to subClassOf (<- i can't put it in bold.)
ns:LivingThing -> http://somewhere#LivingThing (this http has <> but it makes they does not appear)

from rdflib.plugins.sparql import prepareQuery
ns = Namespace("http://somewhere#")
vcard = Namespace("http://www.w3.orq/2001/vcard-rdf/3.0#")
for s,p,o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
  print(s)
q1 = prepareQuery("SELECT ?x WHERE {?x rdfs:subClassOf* <http://somewhere#LivingThing>.}", initNs = {"rdfs": RDFS, "ns": ns})
for r in g.query(q1):
  print(r)

2023-11-19 14:36 UTC, LLLP11 commented on LLLP11 - 22C005/task07.py
> +    print(persona)
q1 = prepareQuery('''
SELECT ?x ?y 
WHERE {
  {?x rdf:type/rdfs:subClassOf* ns:Person}
  UNION
  {?x rdf:type ns:Person}
  }''', initNs = {"rdf":RDF, "ns": ns})
for r in g.query(q1):
  print(r)

2023-11-19 14:37 UTC, LLLP11 commented on LLLP11 - 22C005/task07.py
> +    ?x ?relacion ?a
or elem,p,o in g.triples((None, RDF.type, ns.Animal)):
  for s,t,u in g.triples((elem, None,None)):
    print(s,t,u)
**for elem,p,o in g.triples((None, RDF.type, ns.Person)):
  for s,t,u in g.triples((elem, None,None)):
    print(s,t,u)**
q1 = prepareQuery('''
  SELECT ?x ?relacion
  WHERE {
    {?x rdf:type ns:Animal}
    {?x ?relacion ?a}
    **UNION
    {?x rdf:type ns:Person}
    {?x ?relacion ?a}**
    }
    ''', initNs = {"rdf":RDF, "ns": ns})
for r in g.query(q1):
  print(r)

2023-11-19 14:38 UTC, LLLP11 commented on LLLP11 - 22C005/task07.py
> +    ?x FOAF:knows ns:RockySmith
Same problem with <> in <http://www.w3.org/2001/vcard-rdf/3.0/Given>


foaf = Namespace("http://xmlns.com/foaf/0.1/")
for persona,p,o in g.triples((None, RDF.type, ns.Person)):
  for a,q,r in g.triples((None, foaf.knows, persona)):
    print(a)
q1 = prepareQuery('''
 SELECT ?name
    WHERE {
        ?person foaf:knows ns:RockySmith.
        **?person <http://www.w3.org/2001/vcard-rdf/3.0/Given> ?name**
  }''', initNs = {"rdf": RDF, "ns": ns, "foaf": foaf}
  )
for r in g.query(q1):
  print(r)

2023-11-19 14:39 UTC, LLLP11 commented on LLLP11 - 22C005/task07.py
> +    ?x FOAF:knows ?y
lista = []
lista_def = []
for n,s, o in g.triples((None, FOAF.knows, None)):
  if s in lista:
    lista_def += [s]
  lista += [s]
print(lista_def)
q1 = prepareQuery('''
  SELECT ?x ?person1 ?person2
  WHERE{
    ?x foaf:knows ?person1.
    ?x foaf:knows ?person2.
    FILTER(?person1 != ?person2)
  }''', initNs = {"rdf": RDF, "ns": ns, "FOAF":FOAF}
)
for r in g.query(q1):
  print(r)

2023-11-20 11:53 UTC, dgarijo commented
Implement the changes in this PR, or open a new PR, reference this one and close this one.

2023-11-21 22:24 UTC, dgarijo requested changes
There are still issues

2023-11-21 22:24 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +q1 = prepareQuery("SELECT ?x WHERE {?x rdfs:subClassOf* http://somewhere#LivingThing.}", initNs = {"rdfs": RDFS, "ns": ns})
You have not run this query, it's malformed

2023-11-21 22:24 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +for s,p,o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
this does not retrieve all subclasses of subclasses of living thing

2023-11-21 22:24 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +        {?x rdf:type ns:Person}
```
UNION
        {?x rdf:type ns:Person}
``` 
is redundant

2023-11-21 22:24 UTC, dgarijo commented on LLLP11 - 22C005/task07.py
> +        ?person http://www.w3.org/2001/vcard-rdf/3.0/Given ?name
this query is malformed

2023-11-23 23:04 UTC, anaigmo commented
Entregado con algún fallo, no se admiten más PR

2023-11-23 23:05 UTC, anaigmo commented
No sigue las instrucciones de entrega, así que no se hace merge

2023-11-23 23:05 UTC, closed without merging