Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #45
Opened 2023-10-16 21:08 UTC by alvarohuisman

Entrega del Assignmet 4 (con algunas dudas en el Task 07)

2023-11-13 17:20 UTC, dgarijo requested changes
Please have a look at my comments

2023-11-13 17:20 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task06.py
> +g.add((ns.JaneSmith, vcard.Work, Literal('UPM', datatype=XSD.string)))
Work is not defined in vcard.

2023-11-13 17:20 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task07 (1).py
> +    ?Subject rdfs:subClassOf ?LivingThing.
missing recursive query

2023-11-13 17:20 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task07 (1).py
> +  }
This should be done in a single query, without having to list all classes by hand!
Use property chains

2023-11-13 17:20 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task07 (1).py
> +    ?Subject rdf:type ?Person.
You are requested to print the name of the persons

2023-11-13 17:20 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task07 (1).py
> +# **Task 7.5: List the entities who know at least two other entities in the graph**
missing.

And missing all exercises in rdflib

2023-11-21 23:08 UTC, dgarijo requested changes
Please fix issues and missing exercises

2023-11-21 23:08 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task_07.py
> +    ?Subject rdfs:subClassOf ?LivingThing.
missing subclasses of subclasses of living thing

2023-11-21 23:08 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task_07.py
> +  ''',
Use a single query!

2023-11-21 23:08 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task_07.py
> +  }
Use both in a single query

2023-11-21 23:08 UTC, dgarijo commented on Assignment4/alvarohuisman-22C029/Task_07.py
> +
Missing exercises in rdflib (7.1 .. 7.5)

2023-11-22 10:28 UTC, alvarohuisman commented
Added all corrections and missing excercises, thank you

2023-11-23 23:03 UTC, anaigmo commented
Entregado y corregido, no se admiten más PR

2023-11-23 23:03 UTC, merged