Assignament 4
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #49
Opened 2023-10-16 22:00 UTC by ALBALOZANOG

Alba Lozano

2023-10-31 17:09 UTC, SerPablo commented
Please, review exercises 7.1 7.2 and 7.3 including rdflib

2023-11-14 23:40 UTC, dgarijo requested changes
Additional comments to the ones raised already

2023-11-14 23:40 UTC, dgarijo commented on Assignment4/AlbaLozano_22C025/task06.py
> +g.add((JaneSmith, ns3.gIVEN, given_name))
it should be GIVEN. Capitalization is important

2023-11-14 23:40 UTC, dgarijo commented on Assignment4/AlbaLozano_22C025/albalozano_22c025.py
> +g.add((ns.A, FOAF.knows, ns.B))
I don't understand what you are trying to do here

2023-11-20 11:48 UTC, dgarijo requested changes
Missing exercises.

2023-11-20 11:48 UTC, dgarijo commented on Assignment4/AlbaLozano_22C025/task07.py
> +  print(r)
You are not retrieving the full subclass hierarchy of LivingThing

2023-11-20 11:48 UTC, dgarijo commented on Assignment4/AlbaLozano_22C025/task07.py
> +    print(r.entity)
Missing all exercises in rdflib

2023-11-23 22:56 UTC, anaigmo commented
Entregado, falta algún ejercicio pero mayormente corregido, no se admiten más PR

2023-11-23 22:56 UTC, merged