Assignement 4 Natalia Figal
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #54
Opened 2023-10-16 22:24 UTC by nataliafigal

2023-10-31 11:27 UTC, SerPablo commented
Comments, 

please finish the exercises such as 7.5. Hint for 7.5:
?Subject xxxxxxxxxxxxxxxxxxxxx. xxxxxxxx
filter(?b != ?c)

Please check files and folders to be merged. In this pull request there are two folders. Remove one. Files have to be reflected in Assignment4/{name_or_id}/{files}
Task9 should not be in this pull request

2023-10-31 11:29 UTC, SerPablo commented
Please complete task7 in both rdflib and SPARQL.

2023-11-21 23:11 UTC, dgarijo requested changes
Half of the exersises are missing

2023-11-21 23:11 UTC, dgarijo commented on Assignment4/natalia figal- 22C051/copia_de_task06.py
> +g.add((ns.JaneSmith, VCARD.GIVEN, Literal("Jane")))
GIVEN is not in vcard (see capitalization). 
Also, family name (line below) is not there. Search for the right properties

2023-11-21 23:11 UTC, dgarijo commented on Assignment4/natalia figal- 22C051/copia_de_task07.py
> +
!! missing

2023-11-23 22:46 UTC, anaigmo commented
Entregado y corregido, aunque falta algún ejercicio. No se admiten más PR.

2023-11-23 22:46 UTC, merged