Laura
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #55
Opened 2023-10-16 22:38 UTC by CHAPIICHAP

2023-10-31 11:05 UTC, SerPablo commented
Please, check that  the exercises in task7 have to be in rdflib and sparql. Complete those that have only one solution

2023-11-14 23:34 UTC, dgarijo requested changes
Additional comments to review

2023-11-14 23:34 UTC, dgarijo commented on Assignment4/ChapiiChap - 22C017/task07.py
> +  print(s)
does not go through the subclasses of subclasses of rdf lib

2023-11-14 23:34 UTC, dgarijo commented on Assignment4/ChapiiChap - 22C017/task07.py
> +?subc rdfs:subClassOf ns:LivingThing.
same as above

2023-11-14 23:34 UTC, dgarijo commented on Assignment4/ChapiiChap - 22C017/task07.py
> +}"""
same as above. You may use a/subclassOf*

2023-11-14 23:34 UTC, dgarijo commented on Assignment4/ChapiiChap - 22C017/task07.py
> +?sub rdfs:subClassOf ns:LivingThing.
here is where you need the UNION query, not use LivingThing

2023-11-14 23:34 UTC, dgarijo commented on Assignment4/ChapiiChap - 22C017/task07.py
> +      filter (?entity != ?otherEntity)
You have not tried this query, because you are asking for any entity that has a property with any other entity.

2023-11-23 22:33 UTC, closed without merging

2023-11-23 22:33 UTC, anaigmo commented
Related to https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-DataScience/pull/109