Assigment 4 Eduardo Álvarez
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #60
Opened 2023-10-18 10:58 UTC by edualvareez

2023-10-31 10:56 UTC, SerPablo commented
Try 7.5! 
Hint 

?Subject   xxxxxxxxxxxxxxxxxxxxx. xxxxxxxx
 filter(?b != ?c)

2023-11-14 23:25 UTC, dgarijo requested changes

2023-11-14 23:25 UTC, dgarijo commented on Assignment4/e22c022- 22c022/task07.py
> +  print(s)
not recursive

2023-11-14 23:25 UTC, dgarijo commented on Assignment4/e22c022- 22c022/task07.py
> +  print(s)
You need to print ALL subclasses of living thing (recursively)

2023-11-14 23:25 UTC, dgarijo commented on Assignment4/e22c022- 22c022/task07.py
> +    ?subclass rdfs:subClassOf ns:LivingThing .
same as above

2023-11-14 23:25 UTC, dgarijo commented on Assignment4/e22c022- 22c022/task07.py
> +    print(s2)
This only goes 1 level into subclasses. Hint: do a recursive function

2023-11-14 23:25 UTC, dgarijo commented on Assignment4/e22c022- 22c022/task07.py
> +}
same as above. Use chained operators with `*`

2023-11-14 23:25 UTC, dgarijo commented on Assignment4/e22c022- 22c022/task07.py
> +        ?person ?property ?value.
you need to do the UNION with animal and Person, not living thing

2023-11-14 23:25 UTC, dgarijo commented on Assignment4/e22c022- 22c022/task07.py
> +
missing!

2023-11-23 22:24 UTC, anaigmo commented
Entregado, corregido con algunos fallos, no se admiten más PR

2023-11-23 22:24 UTC, merged