Assignment 4
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #86
Opened 2023-11-13 22:51 UTC by JavierGSorli

Añado la tarea de sparql y la tarea 1 de buscar un csv. Ya que borre el pull request al hacerselo a un compañero para el hands on y creo que subí archivos que no eran.

2023-11-14 23:07 UTC, dgarijo requested changes
Please address the requested changes

2023-11-14 23:07 UTC, dgarijo commented on Assignment4/JavierGSorli-22C018/task06.py
> +g.add((ns.JaneSmith, vcard.hasFamilyName, Literal("Smith")))
vcard does not have hasGivenName, hasEmail, hasFamilyName. Either use the ones defined in the vocabulary, or create your own

2023-11-14 23:07 UTC, dgarijo commented on Assignment4/JavierGSorli-22C018/task07.py
> +    ?Subject rdfs:subClassOf ns:LivingThing.
you are not listing all subclasses recursively

2023-11-14 23:07 UTC, dgarijo commented on Assignment4/JavierGSorli-22C018/task07.py
> +    ?Subject RDF:type ns:Person.
not listing the elements from the subclasses of person

2023-11-14 23:07 UTC, dgarijo commented on Assignment4/JavierGSorli-22C018/task07.py
> +    FILTER (?clase = ns:Animal || ?clase = ns:Person)
use UNION, not a filter which is very inefficient in this case.

2023-11-14 23:07 UTC, dgarijo commented on Assignment4/JavierGSorli-22C018/task07.py
> +    ?Subject RDF:type ns:Person.
you are not returning the name of the person, which is what the exercise demands

2023-11-14 23:07 UTC, dgarijo commented on Assignment4/JavierGSorli-22C018/task07.py
> +  print(r.Subject, r.persona1, r.persona2)
Missing all exercises with rdflib

2023-11-23 22:21 UTC, anaigmo commented
Entregado, corregido con algunos fallos, no se admiten más PR

2023-11-23 22:21 UTC, merged