Assignment4 individual bran faraco
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #89
Opened 2023-11-15 15:18 UTC by branfaraco

Assigment4

2023-11-20 11:47 UTC, dgarijo requested changes
Test your queries before submitting your assignment

2023-11-20 11:47 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task06.py
> +g.add((ns.JaneSmith, VCARD.hasEmail, Literal("jsmith@example.org")))
vcard does not define "hasEmail". Search for the right property in the vocabulary

2023-11-20 11:47 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task06.py
> +g.add((names_node, VCARD.hasGivenName, Literal("Jany")))
same as above for hasFivenName and FamilyName

2023-11-20 11:47 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task06.py
> +g.add((ns.JonhSmith, VCARD.work, ns.UPM))
idem for work

2023-11-20 11:47 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task07.py
> +    ?Subject RDFS.subClassOf ns.LivingThing.
you have not run this query because it's badly formatted. I will not continue my review until you test and fix your queries.

2023-11-20 11:47 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task07.py
> +    ?Subject RDFS.subClassOf ns.LivingThing.
Also, this does not return all the subclass hierarchy of LivingThing

2023-11-20 12:28 UTC, branfaraco commented on Assignment4/Branfaraco-22C049/task06.py
> +g.add((ns.JaneSmith, VCARD.hasEmail, Literal("jsmith@example.org")))
![image](https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-DataScience/assets/144667961/17c2fd9c-cf47-423c-bcb1-36e8c224c694)

2023-11-20 12:30 UTC, branfaraco commented on Assignment4/Branfaraco-22C049/task06.py
> +g.add((ns.JonhSmith, VCARD.work, ns.UPM))
![image](https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-DataScience/assets/144667961/02eb1c70-a86a-484a-bc45-4fb741ce3f31)

2023-11-20 12:37 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task06.py
> +g.add((ns.JonhSmith, VCARD.work, ns.UPM))
It works because you are redefining a term. But https://www.w3.org/2001/vcard-rdf/3.0# does not contain "hasFamilyName". You are creating this property with their namespace, which is wrong.

Imagine you create a specification, and you state that you have "email" as a property. What you are doing is saying "I don't care, now I am going to create 'hasEmail'". But then when you go to the original document, you cannot find it, nor what it means. And therefore, the data integration problem now is worse.

2023-11-20 12:43 UTC, branfaraco commented on Assignment4/Branfaraco-22C049/task06.py
> +g.add((names_node, VCARD.hasGivenName, Literal("Jany")))
Vale, gracias, luego lo cambio.

2023-11-20 12:48 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task07.py
> +    ?Subject RDFS.subClassOf ns.LivingThing.
Has probado a ejecutar la query?
estás usando puntos, cuando deberían ser `:`. Mira los ejemplos que hemos visto en clase

2023-11-21 10:09 UTC, branfaraco commented
Creo que ya lo he cambiado

2023-11-21 22:53 UTC, dgarijo requested changes
There are missing exercises

2023-11-21 22:53 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task06.py
> +g.add((ns.JonhSmith, VCARD.worksat, ns.UPM))
vcard no contiene worksat. Mira el vocabulario y elige una propiedad que exista!

2023-11-21 22:53 UTC, dgarijo commented on Assignment4/Branfaraco-22C049/task07.py
> +
missing exercises 7.1 .. 7.5 in rdflib

2023-11-22 11:02 UTC, branfaraco commented
Lo he cambiado

2023-11-22 11:22 UTC, branfaraco commented
He hecho cambios

2023-11-23 22:16 UTC, anaigmo commented
Entregado y crregido pero con algún fallo, no se admiten más PR

2023-11-23 22:16 UTC, merged