Assigment 4 - Alicia Guzmán
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #92
Opened 2023-11-15 15:35 UTC by alicia-guzman

Vuelvo a subir el pull request del assigment 4 individual porque se me eliminó al cambiar el fork al repositorio del líder en el trabajo en grupo.

Tened en cuenta solo el commit del Assigment 4, los demás son del trabajo en grupo que no sé por qué me siguen apareciendo.

2023-11-15 15:58 UTC, dgarijo requested changes
See edits for missing issues

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task06.py
> +g.add((ns.JaneSmith, VCARD.familynames, Literal("Smith")))
Email address is missing
Capitalization is important. `given` does not exist in vcard (it's `GIVEN`)

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task06.py
> +g.add((ns.JohnSmith,VCARD.works,ns.UPM))
VCARD does not define the works property. Either search for the right property, reuse another vocabulary, or define your own

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +    print(s)
This is not retrieving subclasses of subclasses of LivingThing. Hint: use a recursive function

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +      ?Subject rdfs:subClassOf ns:LivingThing.
Same as above

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +      ?person rdfs:subClassOf ns:Person .
Use only one query. And make it with property chains (`*`)

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +
missing in rdflib

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +    }
See what the exercise states: `You do not need to list the individuals of the subclasses of person`
Why do you then list  the individuals of the subclasses of person or animal?

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +g.add((ns.Jown,VCARD.knows,FOAF.Person))
Why do you add a new entity?

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +        ?personName foaf:knows ns:RockySmith.
?personName foaf:knows Rocky is incorrect. You have not tested this query

2023-11-15 15:58 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +        ?entity ns:knows ?knownEntity2 .
missing a filter to ensure that entity1!=entity2. Missing the exercise in rdflib

2023-11-20 12:08 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +    }
This only lists the items from ns:Animal, not Person

2023-11-20 12:09 UTC, dgarijo commented
Comments are still not addressed

2023-11-21 22:34 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +    print(s)
Pending still

2023-11-21 22:34 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +    people += [s1]
same issue as above (add a recursive function)

2023-11-21 22:36 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +for s, p, o in g.triples((None, FOAF.Knows, ns.Entity1 and ns.Entity2)):
This does not seem correct. ns.Entity1 is a URI!

2023-11-21 22:36 UTC, dgarijo commented on Assignment4/alicia-guzman - 22C014/Task07.py
> +        ?person FOAF:knows "Rocky"
You have not run this query. It's incorrect.

2023-11-21 22:37 UTC, dgarijo requested changes
You are close, but there are still problems.

You should try running the queries, as it shows you haven't run some of them. They are incorrect.

2023-11-23 22:09 UTC, anaigmo commented
Entregado, corregido con algunos fallos, no se admiten más PR

2023-11-23 22:09 UTC, merged