Assignment 4-Miguel Ángel Suárez
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #94
Opened 2023-11-15 19:53 UTC by miguelangel-suarez

Assignment 4 added to the corresponding directory from Miguel Ángel Suárez Ucieda

2023-11-15 23:17 UTC, dgarijo requested changes
Please address the issues highlighted in my review

2023-11-15 23:17 UTC, dgarijo commented on Assignment4/miguelangel-suarez-22c010/task06.py
> +g.add((VCARD.Works_at, RDF.type, RDFS.Datatype))
This is a bad practice: you should not redefine the vocabulary created by another organization. It's like creating your own google.com URI. Instead, define a new property on a new namespace

2023-11-15 23:17 UTC, dgarijo commented on Assignment4/miguelangel-suarez-22c010/task07.py
> +q1 = prepareQuery("SELECT ?x WHERE {?x rdfs:subClassOf ns:LivingThing}", initNs = {"rdfs":RDFS, "ns":ns})
for both sparql and rdflib: you have not added the means to list subclasses of subclasses of living thing. For rdflib, use a recursive function. For sparql, use `*`

2023-11-15 23:17 UTC, dgarijo commented on Assignment4/miguelangel-suarez-22c010/task07.py
> +    print(persona)
same as above

2023-11-15 23:17 UTC, dgarijo commented on Assignment4/miguelangel-suarez-22c010/task07.py
> +  for s,t,u in g.triples((elem,None,None)):
what about Person?

2023-11-15 23:17 UTC, dgarijo commented on Assignment4/miguelangel-suarez-22c010/task07.py
> +    }''', initNs = {"rdf": RDF, "ns": ns}
missing Person

2023-11-15 23:17 UTC, dgarijo commented on Assignment4/miguelangel-suarez-22c010/task07.py
> +    print(a)
You are listing all the entities that know a Person, not what the exercise says

2023-11-15 23:17 UTC, dgarijo commented on Assignment4/miguelangel-suarez-22c010/task07.py
> +            ?x FOAF:knows ns:RockySmith
The exercise is asking to list the names of the person

2023-11-15 23:17 UTC, dgarijo commented on Assignment4/miguelangel-suarez-22c010/task07.py
> +    )
In both rdflib and sparql, you are listing all those who know 1 person, not 2 as the exercise requests

2023-11-19 16:15 UTC, miguelangel-suarez commented
Hope you can see the commits I made for changing the assignment. If any problem or resolution is needed, just tell me.

2023-11-20 11:54 UTC, dgarijo approved these changes

2023-11-20 11:55 UTC, merged