Assigment 4 - Maria del Mar Sierra
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #95
Opened 2023-11-16 15:20 UTC by Mariadelmarsierra

Vuelvo a subir el assigment 4 ya que se eliminó al hacer el fork del repositorio del líder

2023-11-16 17:25 UTC, dgarijo requested changes
Please address the remaining changes

2023-11-16 17:25 UTC, dgarijo commented on Assignment4/Mariadelmarsierra-22c060/task07.py
> +    ?subclass rdfs:subClassOf ns:LivingThing .
You are not addressing the subclasses of subclasses of living thing. Hint: use `*`

2023-11-16 17:25 UTC, dgarijo commented on Assignment4/Mariadelmarsierra-22c060/task07.py
> +    FILTER (?class = ns:Person || ?class = ns:Animal)
very inefficient query. Use UNION instead

2023-11-16 17:25 UTC, dgarijo commented on Assignment4/Mariadelmarsierra-22c060/task07.py
> +  print(row)
Missing all exercises in rdflib

2023-11-16 17:25 UTC, dgarijo commented on Assignment4/Mariadelmarsierra-22c060/task07.py
> +    FILTER (?class = ns:Person || ?class = ns:Animal)
this filter is unrelated to the problem

2023-11-16 17:25 UTC, dgarijo commented on Assignment4/Mariadelmarsierra-22c060/task07.py
> +    FILTER (STR(?knownEntity1) < STR(?knownEntity2))
why compare the strings? just do entity1!= entity2

2023-11-16 17:25 UTC, dgarijo commented on Assignment4/Mariadelmarsierra-22c060/task07.py
> +    BIND(CONCAT(STR(?knownEntity1), ", ", STR(?knownEntity2)) AS ?knownEntities)
note needed

2023-11-23 22:05 UTC, anaigmo commented
Entregado, corregido con algunos fallos, no se admiten más PR

2023-11-23 22:05 UTC, merged