Assigment 4
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #96
Opened 2023-11-16 19:23 UTC by AndreaMejiaCh

tarea 6 y 7

2023-11-17 11:33 UTC, dgarijo requested changes
Please address pending changes

2023-11-17 11:33 UTC, dgarijo commented on Assignment4/andreamejia-22c063/task06_AndreaMejia.py
> +g.add((janeSmithURI,vcard.GIVEN,Literal("Jane")))
the correct prop is Given (check it in vcard)

2023-11-17 11:33 UTC, dgarijo commented on Assignment4/andreamejia-22c063/task07_AndreaMejía.py
> +      ?Subject rdfs:subClassOf ns:LivingThing.
Does not retrieve the subclasses of subclasses of living thing

2023-11-17 11:33 UTC, dgarijo commented on Assignment4/andreamejia-22c063/task07_AndreaMejía.py
> +      ?S rdfs:subClassOf ns:Person.
same issue as above. Use `*`

2023-11-17 11:33 UTC, dgarijo commented on Assignment4/andreamejia-22c063/task07_AndreaMejía.py
> +    ns:RockySmith foaf:knows ?conoce.
You are not returning what the exercise is asking for.

2023-11-17 11:33 UTC, dgarijo commented on Assignment4/andreamejia-22c063/task07_AndreaMejía.py
> +    ?subject foaf:knows ?o.
You are not returning what the exercise is asking for.

Also, no exercises are in rdflib

2023-11-23 21:58 UTC, anaigmo commented
Cierro PR, correcciones en https://github.com/FacultadInformatica-LinkedData/Curso2023-2024-DataScience/pull/97

2023-11-23 21:58 UTC, closed without merging