Asssignmet 4 - Andrea cambios finales
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #97
Opened 2023-11-17 16:23 UTC by AndreaMejiaCh

tarea 6 y 7

2023-11-17 16:30 UTC, dgarijo requested changes
Andrea, do not open a new PR. Work on this one. You are opening pull requests that contain the same errors, and we have to assess them over and over again. 

We will not assess new pull requests unless you do them here so we can see which changes you add

2023-11-17 16:30 UTC, dgarijo commented on Assignment4/andreamejia-22c063/task07_AndreaCambios.py
> +      Optional{?x rdfs:subClassOf ?Subject}
This does not list the subclass hierarchy, just 2 levels. Use a property chain

2023-11-17 16:30 UTC, dgarijo commented on Assignment4/andreamejia-22c063/task07_AndreaCambios.py
> +      ?S rdfs:subClassOf ns:Person.
same issue as above

2023-11-17 16:30 UTC, dgarijo commented on Assignment4/andreamejia-22c063/task07_AndreaCambios.py
> +    ?subject foaf:knows ?o.
This is not doing what the exercise requests.
Also, 7.4 does not return name.
Also, all rdflib exercises are missing.

2023-11-23 22:01 UTC, anaigmo commented
Entregado, corregido pero con fallos y faltan ejercicios, debería haber un archivo por ejercicio

2023-11-23 22:02 UTC, merged