Assignment4individual marcos de miguel
FacultadInformatica-LinkedData/Curso2023-2024-DataScience pull request #98
Opened 2023-11-21 10:08 UTC by branfaraco

Entregando como .py

2023-11-21 22:57 UTC, dgarijo requested changes
The exercises are incomplete

2023-11-21 22:57 UTC, dgarijo commented on Assignment4/marcosdmv-22C031/Task06.py
> +g.add((ns.JohnSmith, vcard.work, ns.UPM))
work is not defined in vcard. Search for a property that is defined in that vocabualry

2023-11-21 22:57 UTC, dgarijo commented on Assignment4/marcosdmv-22C031/Task07.py
> +              ?a rdfs:subClassOf ns:LivingThing
this does not retrieve all subclasses of subclasses of living thing

2023-11-21 22:57 UTC, dgarijo commented on Assignment4/marcosdmv-22C031/Task07.py
> +            ?b rdf:type ?a
same as above

2023-11-21 22:57 UTC, dgarijo commented on Assignment4/marcosdmv-22C031/Task07.py
> +           FILTER(?a foaf:knows ns:RockySmith)
the exercise asks to return  names, not URIs

2023-11-21 22:57 UTC, dgarijo commented on Assignment4/marcosdmv-22C031/Task07.py
> +"""**Task 7.5: List the entities who know at least two other entities in the graph**"""
missing. 

Missing all exercises in rdflib

2023-11-23 21:54 UTC, anaigmo commented
Entregado sin corregir los fallos, no se admiten más PR

2023-11-23 22:31 UTC, merged